version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: drivee-analytics-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: drivee_analytics
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - drivee_pg_data:/var/lib/postgresql/data
      - ./db/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
      - ./db/seed.sql:/docker-entrypoint-initdb.d/02-seed.sql:ro

volumes:
  drivee_pg_data:
